version: "3.9"

services:  
  api:
    image: ucla_swap_api
    container_name: ucla_swap_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4000:4000

  caddy:
    image: caddy:2.6.2-alpine
    container_name: ucla_swap_caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/../client/dist:/usr/share/caddy/client
      - /home/ubuntu/caddy/data:/data
      - /home/ubuntu/caddy/config:/config

volumes:
  caddy_data:
  caddy_config:
  dockerdb:
