version: "3.9"

services:  
  db:
    image: mysql:8.0
    container_name: ucla_swap_sql
    env_file:
      - .env
    command: --default_authentication_plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dockerdb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 30s
      retries: 8
      start_period: 30s

  api:
    image: ucla_swap_api
    container_name: ucla_swap_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4000:4000

volumes:
  dockerdb:
