version: "3.9"

services:  
  api:
    image: ucla_swap_api
    container_name: ucla_swap_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4000:4000

volumes:
  dockerdb:
